import { computed, ref } from 'vue';

export type AppLocale = 'en' | 'uk';

const STORAGE_KEY = 'shared-shelf-locale';

const messages = {
  en: {
    'common.loading': 'Loading...',
    'nav.home': 'Home',
    'nav.books': 'Books',
    'nav.groups': 'Groups',
    'nav.loans': 'Borrowed',
    'nav.notifications': 'Notifications',
    'nav.openProfile': 'Open profile',
    'nav.logout': 'Log out',
    'nav.switchLanguage': 'Switch language',
    'home.title': 'Your reading space',
    'home.description': 'Manage your books, join reading groups, share catalog entries, and keep borrowing requests in one place.',
    'home.collection': 'Collection',
    'home.groups': 'Groups',
    'home.available': 'Available',
    'home.myBooks': 'My books',
    'home.myBooksHint': 'Add and organize your collection',
    'home.groupsHint': 'Find, create, and manage reading groups',
    'home.recent': 'Recent shelf updates',
    'home.latestBooks': 'Latest books',
    'home.viewLibrary': 'View library',
    'home.noBooks': 'No books yet',
    'home.noBooksHint': 'Start your personal shelf with one title. You can share it with groups later.',
    'home.addFirstBook': 'Add first book',
    'home.groupActivity': 'Group activity',
    'home.yourCircles': 'Your groups',
    'home.noGroups': 'No groups yet',
    'home.noGroupsHint': 'Create a private circle or discover open groups.',
    'home.browseGroups': 'Browse groups',
    'home.workflow.addTitle': 'Add books',
    'home.workflow.addText': 'Keep your personal shelf tidy with language, condition, status, and descriptions.',
    'home.workflow.shareTitle': 'Share in groups',
    'home.workflow.shareText': 'Put selected books into a group catalog and control visibility when needed.',
    'home.workflow.requestsTitle': 'Handle requests',
    'home.workflow.requestsText': 'Approve, reject, cancel, return, and review borrowed books through the group view.',
    'home.profileSettings': 'Account settings',
    'home.profileText': 'Update your profile, avatar, bio, and check your reputation score.',
    'home.openProfile': 'Open profile',
    'books.eyebrow': 'Personal collection',
    'books.title': 'My books',
    'books.addBook': 'Add book',
    'books.total': 'Total books',
    'books.ready': 'Ready to share',
    'books.search': 'Search library',
    'books.searchPlaceholder': 'Search by title, author, genre, language',
    'books.status': 'Status',
    'books.sort': 'Sort',
    'books.all': 'All',
    'books.newest': 'Newest',
    'books.titleSort': 'Title',
    'books.authorSort': 'Author',
    'books.grid': 'Grid',
    'books.list': 'List',
    'books.loading': 'Loading books...',
    'books.open': 'Open',
    'books.edit': 'Edit',
    'books.delete': 'Delete',
    'books.genre': 'Genre',
    'books.language': 'Language',
    'books.year': 'Year',
    'books.condition': 'Condition',
    'books.added': 'Added',
    'books.emptyTitle': 'Your collection is empty',
    'books.emptyText': 'Add your first book, then share selected titles with reading groups.',
    'books.countOne': 'book',
    'books.countFew': 'books',
    'books.countMany': 'books',
    'books.summaryLabel': 'Library summary',
    'books.controlsLabel': 'Library controls',
    'books.listLabel': 'Your books',
    'books.viewModeLabel': 'View mode',
    'books.confirmDelete': 'Remove "{title}" from your collection?',
    'bookDetail.back': 'Back to my books',
    'bookDetail.loading': 'Loading book...',
    'bookDetail.details': 'Book details',
    'bookDetail.about': 'About',
    'bookDetail.aboutLabel': 'About book',
    'bookDetail.noDescription': 'No description yet.',
    'bookDetail.owner': 'Owner',
    'bookDetail.reviews': 'Reviews',
    'bookDetail.reviewsLabel': 'Book reviews',
    'bookDetail.reviewOne': 'review',
    'bookDetail.reviewMany': 'reviews',
    'bookDetail.noReviews': 'No reviews yet',
    'bookDetail.noReviewsText': 'Reviews appear after completed loans.',
    'bookDetail.unavailableTitle': 'Book is unavailable',
    'bookDetail.unavailableText': 'We could not load this book right now.',
    'editor.back': 'Back to library',
    'editor.new': 'New book',
    'editor.edit': 'Edit book',
    'editor.newTitle': 'Add a book to your shelf',
    'editor.editTitle': 'Update book details',
    'editor.description': 'Capture the essentials first. You can refine catalog and sharing details later.',
    'editor.complete': 'book details complete',
    'editor.basic': 'Basic info',
    'editor.basicText': 'The title and author are required. Everything else can stay flexible.',
    'editor.details': 'Details',
    'editor.detailsText': 'These help people browse and understand what you are sharing.',
    'editor.availability': 'Availability',
    'editor.availabilityText': 'Set expectations before the book appears in group catalogs.',
    'editor.preview': 'Preview note',
    'editor.previewText': 'A short note makes the card feel personal without overwhelming readers.',
    'editor.titleLabel': 'Title',
    'editor.authorLabel': 'Author',
    'editor.cover': 'Cover photo',
    'editor.coverHint': 'Click to add a cover image.',
    'editor.coverTypeError': 'Please choose an image file.',
    'editor.coverSizeError': 'Cover image must be 3 MB or smaller.',
    'editor.descriptionLabel': 'Description',
    'editor.notSpecified': 'Not specified',
    'editor.isbn': 'ISBN',
    'editor.titlePlaceholder': 'Book title',
    'editor.authorPlaceholder': 'Author name',
    'editor.genrePlaceholder': 'Literary fiction',
    'editor.yearPlaceholder': '2024',
    'editor.conditionPlaceholder': 'Good, hardcover, annotated...',
    'editor.descriptionPlaceholder': 'Why this copy is worth borrowing, edition notes, or exchange preferences.',
    'editor.formCompletionLabel': 'Form completion',
    'editor.loading': 'Loading book...',
    'editor.save': 'Save changes',
    'editor.add': 'Add book',
    'editor.cancel': 'Cancel',
    'editor.view': 'View book',
    'groups.eyebrow': 'Reading groups',
    'groups.title': 'Groups',
    'groups.subtitle': 'Create private reading rooms, discover open groups, and share catalog shelves with people you trust.',
    'groups.sections': 'Group sections',
    'groups.myGroups': 'My groups',
    'groups.discover': 'Discover',
    'groups.invitations': 'Invitations',
    'groups.yourGroups': 'Your groups',
    'groups.myGroupsText': 'Groups where your membership is active.',
    'groups.loading': 'Loading groups...',
    'groups.open': 'Open',
    'groups.private': 'Private',
    'groups.inviteCode': 'Invite code',
    'groups.openGroup': 'Open group',
    'groups.edit': 'Edit',
    'groups.editGroup': 'Edit group',
    'groups.editText': 'Update the group name, description, or visibility.',
    'groups.save': 'Save changes',
    'groups.cancelEdit': 'Cancel edit',
    'groups.leave': 'Leave group',
    'groups.leaveConfirm': 'Leave "{name}"?',
    'groups.emptyMine': 'No groups yet',
    'groups.emptyMineText': 'Create a group or join one below.',
    'groups.joinPrivate': 'Join private group',
    'groups.joinPrivateText': 'Use an invite code from another member.',
    'groups.invitePlaceholder': 'Paste code',
    'groups.joinPrivateButton': 'Join private',
    'groups.create': 'Create group',
    'groups.createText': 'Private groups generate an invite code automatically.',
    'groups.name': 'Name',
    'groups.description': 'Description',
    'groups.descriptionPlaceholder': 'What this group reads or how members exchange books.',
    'groups.visibility': 'Visibility',
    'groups.privateHelp': 'Best for invite-only groups. An invite code will be generated.',
    'groups.openHelp': 'Anyone can find and join this group.',
    'groups.findOpen': 'Find open groups',
    'groups.findOpenText': 'Search public groups you can join directly.',
    'groups.search': 'Search',
    'groups.searchPlaceholder': 'Group name',
    'groups.join': 'Join',
    'groups.emptyDiscover': 'No open groups found',
    'groups.emptyDiscoverText': 'Try another search or create your own group.',
    'groups.loadError': 'Could not load your groups.',
    'groups.searchError': 'Could not search groups.',
    'groups.createError': 'Could not create group.',
    'groups.updateError': 'Could not update group.',
    'groups.joinError': 'Could not join group.',
    'groups.joinPrivateError': 'Could not join private group.',
    'groups.leaveError': 'Could not leave group.',
    'groups.created': '"{name}" was created.',
    'groups.updated': '"{name}" was updated.',
    'groups.joined': 'You joined "{name}".',
    'groups.left': 'You left "{name}".',
    'profile.account': 'Account settings',
    'profile.title': 'Profile',
    'profile.loading': 'Loading profile...',
    'profile.changeAvatar': 'Change avatar',
    'profile.uploading': 'Uploading...',
    'profile.uploadingAvatar': 'Uploading avatar...',
    'profile.reputation': 'Reputation',
    'profile.memberSince': 'Member since',
    'profile.email': 'Email',
    'profile.firstName': 'First name',
    'profile.lastName': 'Last name',
    'profile.bio': 'Bio',
    'profile.bioPlaceholder': 'A short note about your reading taste, exchange preferences, or favorite shelves.',
    'profile.bioHelp': 'This may be visible to people you share books with. Never include passwords or private tokens.',
    'profile.bioWarning': 'Do not store passwords, tokens, API keys, or other sensitive data in your public bio.',
    'profile.save': 'Save profile',
    'profile.reset': 'Reset changes',
    'profile.notAvailable': 'Not available',
    'profile.updated': 'Profile updated successfully.',
    'profile.avatarUpdated': 'Avatar updated successfully.',
    'profile.avatarTypeError': 'Please choose an image file.',
    'profile.avatarSizeError': 'Avatar must be 5 MB or smaller.',
    'profile.genericError': 'Something went wrong. Please try again.',
    'profile.unavailable': 'Profile is unavailable',
    'profile.unavailableText': 'We could not load account data right now. Please refresh the page.',
    'status.available': 'Available',
    'status.unavailable': 'Unavailable',
    'status.borrowed': 'Borrowed',
    'status.queued': 'Queued',
    'status.pending': 'Pending',
    'status.approved': 'Approved',
    'status.rejected': 'Rejected',
    'status.fulfilled': 'Fulfilled',
    'status.canceled': 'Canceled',
    'status.cancelled': 'Canceled',
    'status.returned': 'Returned',
    'status.overdue': 'Overdue',
    'status.active': 'Active',
    'status.lost': 'Lost',
    'status.expired': 'Expired',
    'role.owner': 'Owner',
    'role.admin': 'Admin',
    'role.member': 'Member',
    'role.active': 'Active',
    'role.blocked': 'Blocked',
    'role.pending': 'Pending',
    'groupDetail.back': 'Back to groups',
    'groupDetail.loadingGroup': 'Loading group...',
    'groupDetail.details': 'Group details',
    'groupDetail.catalogEyebrow': 'Group catalog',
    'groupDetail.editDetails': 'Edit group details',
    'groupDetail.ownerEditHint': 'Only the owner can update group details.',
    'groupDetail.book': 'book',
    'groupDetail.books': 'books',
    'groupDetail.addBook': 'Add your book',
    'groupDetail.addBookText': 'Choose one of your books that is not in this catalog yet.',
    'groupDetail.bookLabel': 'Book',
    'groupDetail.selectBook': 'Select a book',
    'groupDetail.addToCatalog': 'Add to catalog',
    'groupDetail.noBooksToAdd': 'All your books are already in this catalog, or your personal collection is empty.',
    'groupDetail.members': 'Members',
    'groupDetail.member': 'member',
    'groupDetail.membersCount': 'members',
    'groupDetail.transferOwnership': 'Transfer ownership',
    'groupDetail.selectMember': 'Select member',
    'groupDetail.loadingMembers': 'Loading members...',
    'groupDetail.changeMemberRole': 'Change member role',
    'groupDetail.block': 'Block',
    'groupDetail.unblock': 'Unblock',
    'groupDetail.noMembers': 'No members found',
    'groupDetail.noMembersText': 'Membership data is not available yet.',
    'groupDetail.catalog': 'Catalog',
    'groupDetail.loadingCatalog': 'Loading catalog...',
    'groupDetail.borrowRequests': 'Borrow requests',
    'groupDetail.removeBookConfirm': 'Remove "{title}" from this catalog?',
    'groupDetail.rejectRequestConfirm': 'Reject request from {username}?',
    'groupDetail.cancelRequestConfirm': 'Cancel this borrow request?',
    'groupDetail.removeMemberConfirm': 'Remove {username} from this group?',
    'groupDetail.blockMemberConfirm': 'Block {username}?',
    'groupDetail.transferConfirm': 'Transfer ownership to {username}?',
    'groupDetail.unavailable': 'Group is unavailable',
    'groupDetail.unavailableText': 'We could not load this group right now.',
    'groupDetail.owner': 'Owner',
    'groupDetail.hidden': 'Hidden',
    'groupDetail.hide': 'Hide',
    'groupDetail.show': 'Show',
    'groupDetail.remove': 'Remove',
    'groupDetail.queue': 'Queue',
    'groupDetail.message': 'Message',
    'groupDetail.messagePlaceholder': 'Optional note for the owner',
    'groupDetail.requestBook': 'Request book',
    'groupDetail.cancel': 'Cancel',
    'groupDetail.dueAt': 'Due at',
    'groupDetail.notes': 'Notes',
    'groupDetail.optional': 'Optional',
    'groupDetail.approve': 'Approve',
    'groupDetail.reject': 'Reject',
    'groupDetail.noRequests': 'No requests yet.',
    'groupDetail.activeLoan': 'Active loan',
    'groupDetail.borrowedBy': 'Borrowed by',
    'groupDetail.due': 'due',
    'groupDetail.ownerLoanHint': 'The borrower should mark this book as returned after handoff.',
    'groupDetail.borrowerLoanHint': 'You received this book. Mark it as returned when you give it back.',
    'groupDetail.returnNotes': 'Return notes',
    'groupDetail.returnPlaceholder': 'Condition after reading or handoff details',
    'groupDetail.returnBook': 'Return book',
    'groupDetail.reviewThisBook': 'Review this book',
    'groupDetail.rating': 'Rating',
    'groupDetail.comment': 'Comment',
    'groupDetail.reviewPlaceholder': 'Optional review',
    'groupDetail.publishReview': 'Publish review',
    'groupDetail.reviews': 'Reviews',
    'groupDetail.noReviews': 'No reviews yet.',
    'groupDetail.returnCondition': 'Return condition',
    'groupDetail.emptyCatalog': 'Catalog is empty',
    'groupDetail.emptyCatalogText': 'Add a book from your collection to start this group shelf.',
    'groupDetail.loadError': 'Could not load group.',
    'groupDetail.bookAdded': 'Book added to group catalog.',
    'groupDetail.addBookError': 'Could not add book to catalog.',
    'groupDetail.borrowRequestCreated': 'Borrow request created.',
    'groupDetail.borrowRequestCreateError': 'Could not create borrow request.',
    'groupDetail.chooseDueDate': 'Choose a due date before approving.',
    'groupDetail.borrowRequestApproved': 'Borrow request approved.',
    'groupDetail.borrowRequestApprovedWithLoan': 'Borrow request approved and loan created.',
    'groupDetail.borrowRequestApproveError': 'Could not approve request.',
    'groupDetail.borrowRequestRejected': 'Borrow request rejected.',
    'groupDetail.borrowRequestRejectError': 'Could not reject request.',
    'groupDetail.borrowRequestCancelled': 'Borrow request cancelled.',
    'groupDetail.borrowRequestCancelError': 'Could not cancel request.',
    'groupDetail.loanReturned': 'Loan returned.',
    'groupDetail.loanReturnedNextActive': 'Loan returned. Next approved request became active.',
    'groupDetail.returnLoanError': 'Could not return loan.',
    'groupDetail.ratingError': 'Choose a rating from 1 to 5.',
    'groupDetail.reviewPublished': 'Review published.',
    'groupDetail.reviewError': 'Could not publish review.',
    'groupDetail.catalogEntryHidden': 'Catalog entry hidden.',
    'groupDetail.catalogEntryVisible': 'Catalog entry visible again.',
    'groupDetail.catalogEntryUpdateError': 'Could not update catalog entry.',
    'groupDetail.bookRemoved': 'Book removed from group catalog.',
    'groupDetail.removeBookError': 'Could not remove catalog entry.',
    'groupDetail.memberRoleUpdated': "{username}'s role was updated.",
    'groupDetail.memberRoleUpdateError': 'Could not update member role.',
    'groupDetail.memberRemoved': '{username} was removed from the group.',
    'groupDetail.memberRemoveError': 'Could not remove member.',
    'groupDetail.memberBlocked': '{username} was blocked.',
    'groupDetail.memberBlockError': 'Could not block member.',
    'groupDetail.memberUnblocked': '{username} was unblocked.',
    'groupDetail.memberUnblockError': 'Could not unblock member.',
    'groupDetail.ownershipTransferred': 'Ownership was transferred.',
    'groupDetail.transferOwnershipError': 'Could not transfer ownership.',
    'groupDetail.leaveError': 'Could not leave group.',
    'loans.eyebrow': 'Borrowed shelf',
    'loans.title': 'Borrowed books',
    'loans.subtitle': 'Books that group owners have handed to you. Return them from here when you give them back.',
    'loans.active': 'Active loans',
    'loans.loading': 'Loading borrowed books...',
    'loans.owner': 'Owner',
    'loans.dueAt': 'Due at',
    'loans.returnNotes': 'Return condition',
    'loans.returnPlaceholder': 'Condition after reading or handoff details',
    'loans.returnBook': 'Return book',
    'loans.emptyTitle': 'No borrowed books',
    'loans.emptyText': 'When an owner gives you a requested book, it will appear here.',
    'loans.loadError': 'Could not load borrowed books.',
    'loans.returnError': 'Could not return this book.',
    'loans.returned': '"{title}" was returned.',
    'loans.readyToReview': '"{title}" was returned. You can leave a review now.',
    'loans.returnedStatus': 'Returned',
    'loans.reviewTitle': 'How was this book?',
    'loans.reviewText': 'Share a short review for the group catalog. Your return condition note will be shown separately.',
    'loans.rating': 'Rating',
    'loans.comment': 'Comment',
    'loans.reviewPlaceholder': 'What did you think about the book?',
    'loans.publishReview': 'Publish review',
    'loans.skipReview': 'Skip review',
    'loans.ratingError': 'Choose a rating from 1 to 5.',
    'loans.reviewError': 'Could not publish review.',
    'loans.reviewPublished': 'Review for "{title}" was published.',
    'loans.conditionShownWithReview': 'This condition note will be shown with your review.',
    'notifications.eyebrow': 'Notification center',
    'notifications.title': 'Notifications',
    'notifications.subtitle': 'Loan reminders, overdue alerts, and request updates from your shared shelf.',
    'notifications.unread': 'Unread',
    'notifications.controlsLabel': 'Notification controls',
    'notifications.listLabel': 'Your notifications',
    'notifications.refresh': 'Refresh',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.loading': 'Loading notifications...',
    'notifications.read': 'Read',
    'notifications.unreadBadge': 'Unread',
    'notifications.openLoan': 'Open borrowed books',
    'notifications.emptyTitle': 'No notifications',
    'notifications.emptyText': 'Reminders and request updates will appear here.',
    'notifications.loadError': 'Could not load notifications.',
    'notifications.markedRead': 'All notifications were marked as read.',
    'notifications.markReadError': 'Could not mark notifications as read.',
    'notifications.someone': 'Someone',
    'notifications.typeName.request_created': 'Request',
    'notifications.typeName.request_approved': 'Request',
    'notifications.typeName.request_rejected': 'Request',
    'notifications.typeName.loan_reminder': 'Reminder',
    'notifications.typeName.loan_overdue': 'Overdue',
    'notifications.typeName.book_returned': 'Return',
    'notifications.type.requestCreated': 'Borrow request created',
    'notifications.type.requestApproved': 'Borrow request approved',
    'notifications.type.requestRejected': 'Borrow request rejected',
    'notifications.type.loanReminder': 'Book return reminder',
    'notifications.type.loanOverdue': 'Loan is overdue',
    'notifications.type.bookReturned': 'Book returned',
    'notifications.body.requestCreated': 'A new borrow request needs attention.',
    'notifications.body.requestCreatedWithBook': '{username} requested "{title}".',
    'notifications.body.requestApproved': 'Your borrow request was approved.',
    'notifications.body.requestApprovedWithBook': 'Your request for "{title}" was approved.',
    'notifications.body.requestRejected': 'Your borrow request was rejected.',
    'notifications.body.requestRejectedWithBook': 'Your request for "{title}" was rejected.',
    'notifications.body.loanReminder': 'Please return "{title}" by {date}.',
    'notifications.body.loanReminderGeneric': 'A borrowed book is due soon.',
    'notifications.body.loanOverdue': 'Your loan for "{title}" is overdue since {date}.',
    'notifications.body.loanOverdueGeneric': 'One of your loans is overdue.',
    'notifications.body.bookReturned': 'A borrowed book was returned.',
    'notifications.body.bookReturnedWithBook': '{username} returned "{title}".',
    'language.ukrainian': 'Ukrainian',
    'language.english': 'English',
    'language.german': 'German',
    'language.french': 'French',
    'language.spanish': 'Spanish',
    'language.italian': 'Italian',
    'language.polish': 'Polish',
    'language.czech': 'Czech',
    'language.slovak': 'Slovak',
    'language.romanian': 'Romanian',
    'language.lithuanian': 'Lithuanian',
    'language.latvian': 'Latvian',
    'language.estonian': 'Estonian',
    'language.portuguese': 'Portuguese',
    'language.dutch': 'Dutch',
    'language.swedish': 'Swedish',
    'language.norwegian': 'Norwegian',
    'language.danish': 'Danish',
    'language.finnish': 'Finnish',
    'language.greek': 'Greek',
    'language.turkish': 'Turkish',
    'language.arabic': 'Arabic',
    'language.hebrew': 'Hebrew',
    'language.chinese': 'Chinese',
    'language.japanese': 'Japanese',
    'language.korean': 'Korean',
  },
  uk: {
    'common.loading': 'Завантаження...',
    'nav.home': 'Головна',
    'nav.books': 'Книги',
    'nav.groups': 'Групи',
    'nav.loans': 'Позичені',
    'nav.notifications': 'Сповіщення',
    'nav.openProfile': 'Відкрити профіль',
    'nav.logout': 'Вийти',
    'nav.switchLanguage': 'Змінити мову',
    'home.title': 'Ваш читацький простір',
    'home.description': 'Керуйте книгами, вступайте в читацькі групи, діліться каталогами та відстежуйте заявки в одному місці.',
    'home.collection': 'Колекція',
    'home.groups': 'Групи',
    'home.available': 'Доступні',
    'home.myBooks': 'Мої книги',
    'home.myBooksHint': 'Додавайте й упорядковуйте свою колекцію',
    'home.groupsHint': 'Знаходьте, створюйте й керуйте читацькими групами',
    'home.recent': 'Останні оновлення',
    'home.latestBooks': 'Нові книги',
    'home.viewLibrary': 'Відкрити бібліотеку',
    'home.noBooks': 'Книг ще немає',
    'home.noBooksHint': 'Додайте першу книгу. Пізніше її можна буде поширити в групах.',
    'home.addFirstBook': 'Додати першу книгу',
    'home.groupActivity': 'Активність груп',
    'home.yourCircles': 'Ваші групи',
    'home.noGroups': 'Груп ще немає',
    'home.noGroupsHint': 'Створіть приватну групу або перегляньте відкриті.',
    'home.browseGroups': 'Переглянути групи',
    'home.workflow.addTitle': 'Додавайте книги',
    'home.workflow.addText': 'Зберігайте мову, стан, статус і опис кожної книги.',
    'home.workflow.shareTitle': 'Діліться в групах',
    'home.workflow.shareText': 'Додавайте вибрані книги в каталог групи та керуйте видимістю.',
    'home.workflow.requestsTitle': 'Обробляйте заявки',
    'home.workflow.requestsText': 'Підтверджуйте, відхиляйте, скасовуйте, повертайте й оцінюйте позики.',
    'home.profileSettings': 'Налаштування акаунта',
    'home.profileText': 'Оновіть профіль, аватар, біо та перегляньте репутацію.',
    'home.openProfile': 'Відкрити профіль',
    'books.eyebrow': 'Особиста колекція',
    'books.title': 'Мої книги',
    'books.addBook': 'Додати книгу',
    'books.total': 'Усього книг',
    'books.ready': 'Готові ділитися',
    'books.search': 'Пошук у бібліотеці',
    'books.searchPlaceholder': 'Назва, автор, жанр або мова',
    'books.status': 'Статус',
    'books.sort': 'Сортування',
    'books.all': 'Усі',
    'books.newest': 'Новіші',
    'books.titleSort': 'Назва',
    'books.authorSort': 'Автор',
    'books.grid': 'Сітка',
    'books.list': 'Список',
    'books.loading': 'Завантаження книг...',
    'books.open': 'Відкрити',
    'books.edit': 'Редагувати',
    'books.delete': 'Видалити',
    'books.genre': 'Жанр',
    'books.language': 'Мова',
    'books.year': 'Рік',
    'books.condition': 'Стан',
    'books.added': 'Додано',
    'books.emptyTitle': 'Колекція порожня',
    'books.emptyText': 'Додайте першу книгу, а потім поширюйте вибрані книги в групах.',
    'books.countOne': 'книга',
    'books.countFew': 'книги',
    'books.countMany': 'книг',
    'books.summaryLabel': 'Підсумок бібліотеки',
    'books.controlsLabel': 'Керування бібліотекою',
    'books.listLabel': 'Ваші книги',
    'books.viewModeLabel': 'Режим перегляду',
    'books.confirmDelete': 'Видалити "{title}" з вашої колекції?',
    'bookDetail.back': 'Назад до моїх книг',
    'bookDetail.loading': 'Завантаження книги...',
    'bookDetail.details': 'Деталі книги',
    'bookDetail.about': 'Про книгу',
    'bookDetail.aboutLabel': 'Про книгу',
    'bookDetail.noDescription': 'Опису ще немає.',
    'bookDetail.owner': 'Власник',
    'bookDetail.reviews': 'Відгуки',
    'bookDetail.reviewsLabel': 'Відгуки про книгу',
    'bookDetail.reviewOne': 'відгук',
    'bookDetail.reviewMany': 'відгуків',
    'bookDetail.noReviews': 'Відгуків ще немає',
    'bookDetail.noReviewsText': 'Відгуки з’являться після завершених позик.',
    'bookDetail.unavailableTitle': 'Книга недоступна',
    'bookDetail.unavailableText': 'Не вдалося завантажити цю книгу зараз.',
    'editor.back': 'Назад до бібліотеки',
    'editor.new': 'Нова книга',
    'editor.edit': 'Редагування книги',
    'editor.newTitle': 'Додайте книгу на свою полицю',
    'editor.editTitle': 'Оновіть дані книги',
    'editor.description': 'Спершу заповніть основне. Каталог і поширення можна уточнити пізніше.',
    'editor.complete': 'даних книги заповнено',
    'editor.basic': 'Основна інформація',
    'editor.basicText': 'Назва й автор обов’язкові. Решту можна заповнити пізніше.',
    'editor.details': 'Деталі',
    'editor.detailsText': 'Це допоможе іншим краще знаходити й розуміти книгу.',
    'editor.availability': 'Доступність',
    'editor.availabilityText': 'Вкажіть очікування перед появою книги в каталогах груп.',
    'editor.preview': 'Короткий опис',
    'editor.previewText': 'Невелика нотатка робить картку книги зрозумілішою та живішою.',
    'editor.titleLabel': 'Назва',
    'editor.authorLabel': 'Автор',
    'editor.cover': 'Фото обкладинки',
    'editor.coverHint': 'Натисніть, щоб додати зображення обкладинки.',
    'editor.coverTypeError': 'Будь ласка, оберіть файл зображення.',
    'editor.coverSizeError': 'Зображення обкладинки має бути не більше 3 МБ.',
    'editor.descriptionLabel': 'Опис',
    'editor.notSpecified': 'Не вказано',
    'editor.isbn': 'ISBN',
    'editor.titlePlaceholder': 'Назва книги',
    'editor.authorPlaceholder': 'Ім’я автора',
    'editor.genrePlaceholder': 'Художня література',
    'editor.yearPlaceholder': '2024',
    'editor.conditionPlaceholder': 'Хороший стан, тверда обкладинка, є нотатки...',
    'editor.descriptionPlaceholder': 'Чим ця книга може зацікавити, особливості видання або побажання щодо обміну.',
    'editor.formCompletionLabel': 'Заповнення форми',
    'editor.loading': 'Завантаження книги...',
    'editor.save': 'Зберегти',
    'editor.add': 'Додати книгу',
    'editor.cancel': 'Скасувати',
    'editor.view': 'Переглянути книгу',
    'groups.eyebrow': 'Читацькі групи',
    'groups.title': 'Групи',
    'groups.subtitle': 'Створюйте приватні читацькі кімнати, знаходьте відкриті групи та діліться каталогами з людьми, яким довіряєте.',
    'groups.sections': 'Розділи груп',
    'groups.myGroups': 'Мої групи',
    'groups.discover': 'Пошук',
    'groups.invitations': 'Запрошення',
    'groups.yourGroups': 'Ваші групи',
    'groups.myGroupsText': 'Групи, де ваша участь активна.',
    'groups.loading': 'Завантаження груп...',
    'groups.open': 'Відкрита',
    'groups.private': 'Приватна',
    'groups.inviteCode': 'Код запрошення',
    'groups.openGroup': 'Відкрити групу',
    'groups.edit': 'Редагувати',
    'groups.editGroup': 'Редагувати групу',
    'groups.editText': 'Оновіть назву, опис або видимість групи.',
    'groups.save': 'Зберегти зміни',
    'groups.cancelEdit': 'Скасувати',
    'groups.leave': 'Вийти з групи',
    'groups.leaveConfirm': 'Вийти з "{name}"?',
    'groups.emptyMine': 'Груп ще немає',
    'groups.emptyMineText': 'Створіть групу або приєднайтесь нижче.',
    'groups.joinPrivate': 'Приєднатися до приватної групи',
    'groups.joinPrivateText': 'Використайте код запрошення від іншого учасника.',
    'groups.invitePlaceholder': 'Вставте код',
    'groups.joinPrivateButton': 'Приєднатися',
    'groups.create': 'Створити групу',
    'groups.createText': 'Для приватних груп код запрошення створюється автоматично.',
    'groups.name': 'Назва',
    'groups.description': 'Опис',
    'groups.descriptionPlaceholder': 'Що читає група або як учасники обмінюються книгами.',
    'groups.visibility': 'Видимість',
    'groups.privateHelp': 'Найкраще для груп лише за запрошенням. Код буде створено автоматично.',
    'groups.openHelp': 'Будь-хто може знайти й приєднатися до цієї групи.',
    'groups.findOpen': 'Знайти відкриті групи',
    'groups.findOpenText': 'Шукайте публічні групи, до яких можна приєднатися одразу.',
    'groups.search': 'Пошук',
    'groups.searchPlaceholder': 'Назва групи',
    'groups.join': 'Приєднатися',
    'groups.emptyDiscover': 'Відкритих груп не знайдено',
    'groups.emptyDiscoverText': 'Спробуйте інший пошук або створіть власну групу.',
    'groups.loadError': 'Не вдалося завантажити ваші групи.',
    'groups.searchError': 'Не вдалося знайти групи.',
    'groups.createError': 'Не вдалося створити групу.',
    'groups.updateError': 'Не вдалося оновити групу.',
    'groups.joinError': 'Не вдалося приєднатися до групи.',
    'groups.joinPrivateError': 'Не вдалося приєднатися до приватної групи.',
    'groups.leaveError': 'Не вдалося вийти з групи.',
    'groups.created': 'Групу "{name}" створено.',
    'groups.updated': 'Групу "{name}" оновлено.',
    'groups.joined': 'Ви приєдналися до "{name}".',
    'groups.left': 'Ви вийшли з "{name}".',
    'profile.account': 'Налаштування акаунта',
    'profile.title': 'Профіль',
    'profile.loading': 'Завантаження профілю...',
    'profile.changeAvatar': 'Змінити аватар',
    'profile.uploading': 'Завантаження...',
    'profile.uploadingAvatar': 'Аватар завантажується...',
    'profile.reputation': 'Репутація',
    'profile.memberSince': 'Учасник з',
    'profile.email': 'Email',
    'profile.firstName': 'Ім’я',
    'profile.lastName': 'Прізвище',
    'profile.bio': 'Біо',
    'profile.bioPlaceholder': 'Коротко про читацькі смаки, обмін книгами або улюблені полиці.',
    'profile.bioHelp': 'Це можуть бачити люди, з якими ви ділитеся книгами. Не додавайте паролі або приватні токени.',
    'profile.bioWarning': 'Не зберігайте паролі, токени, API-ключі або інші чутливі дані в публічному біо.',
    'profile.save': 'Зберегти профіль',
    'profile.reset': 'Скинути зміни',
    'profile.notAvailable': 'Недоступно',
    'profile.updated': 'Профіль успішно оновлено.',
    'profile.avatarUpdated': 'Аватар успішно оновлено.',
    'profile.avatarTypeError': 'Будь ласка, оберіть файл зображення.',
    'profile.avatarSizeError': 'Аватар має бути не більше 5 МБ.',
    'profile.genericError': 'Щось пішло не так. Спробуйте ще раз.',
    'profile.unavailable': 'Профіль недоступний',
    'profile.unavailableText': 'Не вдалося завантажити дані акаунта. Оновіть сторінку.',
    'status.available': 'Доступна',
    'status.unavailable': 'Недоступна',
    'status.borrowed': 'Позичена',
    'status.queued': 'У черзі',
    'status.pending': 'Очікує',
    'status.approved': 'Підтверджено',
    'status.rejected': 'Відхилено',
    'status.fulfilled': 'Виконано',
    'status.canceled': 'Скасовано',
    'status.cancelled': 'Скасовано',
    'status.returned': 'Повернено',
    'status.overdue': 'Прострочено',
    'status.active': 'Активна',
    'status.lost': 'Втрачена',
    'status.expired': 'Прострочена',
    'role.owner': 'Власник',
    'role.admin': 'Адмін',
    'role.member': 'Учасник',
    'role.active': 'Активний',
    'role.blocked': 'Заблокований',
    'role.pending': 'Очікує',
    'groupDetail.back': 'Назад до груп',
    'groupDetail.loadingGroup': 'Завантаження групи...',
    'groupDetail.details': 'Деталі групи',
    'groupDetail.catalogEyebrow': 'Каталог групи',
    'groupDetail.editDetails': 'Редагування деталей групи',
    'groupDetail.ownerEditHint': 'Лише власник може оновлювати деталі групи.',
    'groupDetail.book': 'книга',
    'groupDetail.books': 'книг',
    'groupDetail.addBook': 'Додати свою книгу',
    'groupDetail.addBookText': 'Оберіть книгу зі своєї колекції, якої ще немає в цьому каталозі.',
    'groupDetail.bookLabel': 'Книга',
    'groupDetail.selectBook': 'Оберіть книгу',
    'groupDetail.addToCatalog': 'Додати до каталогу',
    'groupDetail.noBooksToAdd': 'Усі ваші книги вже є в цьому каталозі або особиста колекція порожня.',
    'groupDetail.members': 'Учасники',
    'groupDetail.member': 'учасник',
    'groupDetail.membersCount': 'учасники',
    'groupDetail.transferOwnership': 'Передати власність',
    'groupDetail.selectMember': 'Оберіть учасника',
    'groupDetail.loadingMembers': 'Завантаження учасників...',
    'groupDetail.changeMemberRole': 'Змінити роль учасника',
    'groupDetail.block': 'Заблокувати',
    'groupDetail.unblock': 'Розблокувати',
    'groupDetail.noMembers': 'Учасників не знайдено',
    'groupDetail.noMembersText': 'Дані про учасників поки недоступні.',
    'groupDetail.catalog': 'Каталог',
    'groupDetail.loadingCatalog': 'Завантаження каталогу...',
    'groupDetail.borrowRequests': 'Заявки на позику',
    'groupDetail.removeBookConfirm': 'Видалити "{title}" з цього каталогу?',
    'groupDetail.rejectRequestConfirm': 'Відхилити заявку від {username}?',
    'groupDetail.cancelRequestConfirm': 'Скасувати цю заявку на позику?',
    'groupDetail.removeMemberConfirm': 'Видалити {username} з цієї групи?',
    'groupDetail.blockMemberConfirm': 'Заблокувати {username}?',
    'groupDetail.transferConfirm': 'Передати власність користувачу {username}?',
    'groupDetail.unavailable': 'Група недоступна',
    'groupDetail.unavailableText': 'Не вдалося завантажити цю групу зараз.',
    'groupDetail.owner': 'Власник',
    'groupDetail.hidden': 'Приховано',
    'groupDetail.hide': 'Приховати',
    'groupDetail.show': 'Показати',
    'groupDetail.remove': 'Видалити',
    'groupDetail.queue': 'Черга',
    'groupDetail.message': 'Повідомлення',
    'groupDetail.messagePlaceholder': 'Необов’язкова нотатка для власника',
    'groupDetail.requestBook': 'Запросити книгу',
    'groupDetail.cancel': 'Скасувати',
    'groupDetail.dueAt': 'Повернути до',
    'groupDetail.notes': 'Нотатки',
    'groupDetail.optional': 'Необов’язково',
    'groupDetail.approve': 'Підтвердити',
    'groupDetail.reject': 'Відхилити',
    'groupDetail.noRequests': 'Заявок ще немає.',
    'groupDetail.activeLoan': 'Активна позика',
    'groupDetail.borrowedBy': 'Позичив користувач',
    'groupDetail.due': 'до',
    'groupDetail.ownerLoanHint': 'Позичальник має позначити книгу як повернену після передачі назад.',
    'groupDetail.borrowerLoanHint': 'Ви отримали цю книгу. Позначте її поверненою, коли віддасте назад.',
    'groupDetail.returnNotes': 'Нотатки повернення',
    'groupDetail.returnPlaceholder': 'Стан після читання або деталі передачі',
    'groupDetail.returnBook': 'Повернути книгу',
    'groupDetail.reviewThisBook': 'Оцінити цю книгу',
    'groupDetail.rating': 'Оцінка',
    'groupDetail.comment': 'Коментар',
    'groupDetail.reviewPlaceholder': 'Необов’язковий відгук',
    'groupDetail.publishReview': 'Опублікувати відгук',
    'groupDetail.reviews': 'Відгуки',
    'groupDetail.noReviews': 'Відгуків ще немає.',
    'groupDetail.returnCondition': 'Стан після повернення',
    'groupDetail.emptyCatalog': 'Каталог порожній',
    'groupDetail.emptyCatalogText': 'Додайте книгу зі своєї колекції, щоб почати полицю групи.',
    'groupDetail.loadError': 'Не вдалося завантажити групу.',
    'groupDetail.bookAdded': 'Книгу додано до каталогу групи.',
    'groupDetail.addBookError': 'Не вдалося додати книгу до каталогу.',
    'groupDetail.borrowRequestCreated': 'Заявку на позику створено.',
    'groupDetail.borrowRequestCreateError': 'Не вдалося створити заявку на позику.',
    'groupDetail.chooseDueDate': 'Оберіть дату повернення перед підтвердженням.',
    'groupDetail.borrowRequestApproved': 'Заявку на позику підтверджено.',
    'groupDetail.borrowRequestApprovedWithLoan': 'Заявку на позику підтверджено, позику створено.',
    'groupDetail.borrowRequestApproveError': 'Не вдалося підтвердити заявку.',
    'groupDetail.borrowRequestRejected': 'Заявку на позику відхилено.',
    'groupDetail.borrowRequestRejectError': 'Не вдалося відхилити заявку.',
    'groupDetail.borrowRequestCancelled': 'Заявку на позику скасовано.',
    'groupDetail.borrowRequestCancelError': 'Не вдалося скасувати заявку.',
    'groupDetail.loanReturned': 'Позику повернено.',
    'groupDetail.loanReturnedNextActive': 'Позику повернено. Наступна підтверджена заявка стала активною.',
    'groupDetail.returnLoanError': 'Не вдалося повернути позику.',
    'groupDetail.ratingError': 'Оберіть оцінку від 1 до 5.',
    'groupDetail.reviewPublished': 'Відгук опубліковано.',
    'groupDetail.reviewError': 'Не вдалося опублікувати відгук.',
    'groupDetail.catalogEntryHidden': 'Запис каталогу приховано.',
    'groupDetail.catalogEntryVisible': 'Запис каталогу знову видимий.',
    'groupDetail.catalogEntryUpdateError': 'Не вдалося оновити запис каталогу.',
    'groupDetail.bookRemoved': 'Книгу видалено з каталогу групи.',
    'groupDetail.removeBookError': 'Не вдалося видалити запис каталогу.',
    'groupDetail.memberRoleUpdated': 'Роль користувача {username} оновлено.',
    'groupDetail.memberRoleUpdateError': 'Не вдалося оновити роль учасника.',
    'groupDetail.memberRemoved': 'Користувача {username} видалено з групи.',
    'groupDetail.memberRemoveError': 'Не вдалося видалити учасника.',
    'groupDetail.memberBlocked': 'Користувача {username} заблоковано.',
    'groupDetail.memberBlockError': 'Не вдалося заблокувати учасника.',
    'groupDetail.memberUnblocked': 'Користувача {username} розблоковано.',
    'groupDetail.memberUnblockError': 'Не вдалося розблокувати учасника.',
    'groupDetail.ownershipTransferred': 'Власність передано.',
    'groupDetail.transferOwnershipError': 'Не вдалося передати власність.',
    'groupDetail.leaveError': 'Не вдалося вийти з групи.',
    'loans.eyebrow': 'Позичена полиця',
    'loans.title': 'Позичені книги',
    'loans.subtitle': 'Книги, які власники груп уже передали вам. Поверніть їх тут, коли віддасте назад.',
    'loans.active': 'Активні позики',
    'loans.loading': 'Завантаження позичених книг...',
    'loans.owner': 'Власник',
    'loans.dueAt': 'Повернути до',
    'loans.returnNotes': 'Стан після повернення',
    'loans.returnPlaceholder': 'Стан після читання або деталі передачі',
    'loans.returnBook': 'Повернути книгу',
    'loans.emptyTitle': 'Позичених книг немає',
    'loans.emptyText': 'Коли власник передасть вам запитану книгу, вона з’явиться тут.',
    'loans.loadError': 'Не вдалося завантажити позичені книги.',
    'loans.returnError': 'Не вдалося повернути цю книгу.',
    'loans.returned': 'Книгу "{title}" повернено.',
    'loans.readyToReview': 'Книгу "{title}" повернено. Тепер можна залишити відгук.',
    'loans.returnedStatus': 'Повернено',
    'loans.reviewTitle': 'Як вам ця книга?',
    'loans.reviewText': 'Залиште короткий відгук для каталогу групи. Нотатку про стан буде показано окремо.',
    'loans.rating': 'Оцінка',
    'loans.comment': 'Коментар',
    'loans.reviewPlaceholder': 'Що ви думаєте про книгу?',
    'loans.publishReview': 'Опублікувати відгук',
    'loans.skipReview': 'Пропустити',
    'loans.ratingError': 'Оберіть оцінку від 1 до 5.',
    'loans.reviewError': 'Не вдалося опублікувати відгук.',
    'loans.reviewPublished': 'Відгук про "{title}" опубліковано.',
    'loans.conditionShownWithReview': 'Ця нотатка про стан буде показана разом із вашим відгуком.',
    'notifications.eyebrow': 'Центр сповіщень',
    'notifications.title': 'Сповіщення',
    'notifications.subtitle': 'Нагадування про позики, прострочення та оновлення заявок із вашої спільної полиці.',
    'notifications.unread': 'Непрочитані',
    'notifications.controlsLabel': 'Керування сповіщеннями',
    'notifications.listLabel': 'Ваші сповіщення',
    'notifications.refresh': 'Оновити',
    'notifications.markAllRead': 'Позначити все прочитаним',
    'notifications.loading': 'Завантаження сповіщень...',
    'notifications.read': 'Прочитано',
    'notifications.unreadBadge': 'Нове',
    'notifications.openLoan': 'Відкрити позичені книги',
    'notifications.emptyTitle': 'Сповіщень немає',
    'notifications.emptyText': 'Тут з’являтимуться нагадування та оновлення заявок.',
    'notifications.loadError': 'Не вдалося завантажити сповіщення.',
    'notifications.markedRead': 'Усі сповіщення позначено прочитаними.',
    'notifications.markReadError': 'Не вдалося позначити сповіщення прочитаними.',
    'notifications.someone': 'Хтось',
    'notifications.typeName.request_created': 'Заявка',
    'notifications.typeName.request_approved': 'Заявка',
    'notifications.typeName.request_rejected': 'Заявка',
    'notifications.typeName.loan_reminder': 'Нагадування',
    'notifications.typeName.loan_overdue': 'Прострочення',
    'notifications.typeName.book_returned': 'Повернення',
    'notifications.type.requestCreated': 'Створено заявку на позику',
    'notifications.type.requestApproved': 'Заявку на позику підтверджено',
    'notifications.type.requestRejected': 'Заявку на позику відхилено',
    'notifications.type.loanReminder': 'Нагадування про повернення книги',
    'notifications.type.loanOverdue': 'Позику прострочено',
    'notifications.type.bookReturned': 'Книгу повернено',
    'notifications.body.requestCreated': 'Нова заявка на позику потребує уваги.',
    'notifications.body.requestCreatedWithBook': '{username} запитує книгу "{title}".',
    'notifications.body.requestApproved': 'Вашу заявку на позику підтверджено.',
    'notifications.body.requestApprovedWithBook': 'Вашу заявку на книгу "{title}" підтверджено.',
    'notifications.body.requestRejected': 'Вашу заявку на позику відхилено.',
    'notifications.body.requestRejectedWithBook': 'Вашу заявку на книгу "{title}" відхилено.',
    'notifications.body.loanReminder': 'Будь ласка, поверніть "{title}" до {date}.',
    'notifications.body.loanReminderGeneric': 'Термін повернення позиченої книги скоро настане.',
    'notifications.body.loanOverdue': 'Вашу позику "{title}" прострочено з {date}.',
    'notifications.body.loanOverdueGeneric': 'Одна з ваших позик прострочена.',
    'notifications.body.bookReturned': 'Позичену книгу повернено.',
    'notifications.body.bookReturnedWithBook': '{username} повернув/повернула книгу "{title}".',
    'language.ukrainian': 'Українська',
    'language.english': 'Англійська',
    'language.german': 'Німецька',
    'language.french': 'Французька',
    'language.spanish': 'Іспанська',
    'language.italian': 'Італійська',
    'language.polish': 'Польська',
    'language.czech': 'Чеська',
    'language.slovak': 'Словацька',
    'language.romanian': 'Румунська',
    'language.lithuanian': 'Литовська',
    'language.latvian': 'Латвійська',
    'language.estonian': 'Естонська',
    'language.portuguese': 'Португальська',
    'language.dutch': 'Нідерландська',
    'language.swedish': 'Шведська',
    'language.norwegian': 'Норвезька',
    'language.danish': 'Данська',
    'language.finnish': 'Фінська',
    'language.greek': 'Грецька',
    'language.turkish': 'Турецька',
    'language.arabic': 'Арабська',
    'language.hebrew': 'Іврит',
    'language.chinese': 'Китайська',
    'language.japanese': 'Японська',
    'language.korean': 'Корейська',
  },
} as const;

export type LocalizationKey = keyof typeof messages.en;

const initialLocale = localStorage.getItem(STORAGE_KEY) === 'uk' ? 'uk' : 'en';
const locale = ref<AppLocale>(initialLocale);

export const currentLocale = computed(() => locale.value);
export const localeLabel = computed(() => (locale.value === 'en' ? 'EN' : 'UA'));

export function setLocale(nextLocale: AppLocale) {
  locale.value = nextLocale;
  localStorage.setItem(STORAGE_KEY, nextLocale);
}

export function toggleLocale() {
  setLocale(locale.value === 'en' ? 'uk' : 'en');
}

export function t(key: LocalizationKey) {
  return messages[locale.value][key] ?? messages.en[key] ?? key;
}
