import { computed, ref } from 'vue';

export type AppLocale = 'en' | 'uk';

const STORAGE_KEY = 'shared-shelf-locale';

const messages = {
  en: {
    'nav.home': 'Home',
    'nav.books': 'Books',
    'nav.groups': 'Groups',
    'nav.openProfile': 'Open profile',
    'nav.logout': 'Log out',
    'nav.switchLanguage': 'Switch language',
    'home.title': 'Your reading space',
    'home.description': 'Manage your books, join reading groups, share catalog entries, and keep borrowing requests in one place.',
    'home.collection': 'Collection',
    'home.groups': 'Groups',
    'home.available': 'Available',
    'home.myBooks': 'My books',
    'home.myBooksHint': 'Add and organize your collection',
    'home.groupsHint': 'Find, create, and manage reading groups',
    'home.recent': 'Recent shelf updates',
    'home.latestBooks': 'Latest books',
    'home.viewLibrary': 'View library',
    'home.noBooks': 'No books yet',
    'home.noBooksHint': 'Start your personal shelf with one title. You can share it with groups later.',
    'home.addFirstBook': 'Add first book',
    'home.groupActivity': 'Group activity',
    'home.yourCircles': 'Your groups',
    'home.noGroups': 'No groups yet',
    'home.noGroupsHint': 'Create a private circle or discover open groups.',
    'home.browseGroups': 'Browse groups',
    'home.workflow.addTitle': 'Add books',
    'home.workflow.addText': 'Keep your personal shelf tidy with language, condition, status, and descriptions.',
    'home.workflow.shareTitle': 'Share in groups',
    'home.workflow.shareText': 'Put selected books into a group catalog and control visibility when needed.',
    'home.workflow.requestsTitle': 'Handle requests',
    'home.workflow.requestsText': 'Approve, reject, cancel, return, and review borrowed books through the group view.',
    'home.profileSettings': 'Account settings',
    'home.profileText': 'Update your profile, avatar, bio, and check your reputation score.',
    'home.openProfile': 'Open profile',
    'books.eyebrow': 'Personal collection',
    'books.title': 'My books',
    'books.addBook': 'Add book',
    'books.total': 'Total books',
    'books.ready': 'Ready to share',
    'books.search': 'Search library',
    'books.searchPlaceholder': 'Search by title, author, genre, language',
    'books.status': 'Status',
    'books.sort': 'Sort',
    'books.all': 'All',
    'books.newest': 'Newest',
    'books.titleSort': 'Title',
    'books.authorSort': 'Author',
    'books.grid': 'Grid',
    'books.list': 'List',
    'books.loading': 'Loading books...',
    'books.open': 'Open',
    'books.edit': 'Edit',
    'books.delete': 'Delete',
    'books.genre': 'Genre',
    'books.language': 'Language',
    'books.year': 'Year',
    'books.condition': 'Condition',
    'books.added': 'Added',
    'books.emptyTitle': 'Your collection is empty',
    'books.emptyText': 'Add your first book, then share selected titles with reading groups.',
    'editor.back': 'Back to library',
    'editor.new': 'New book',
    'editor.edit': 'Edit book',
    'editor.newTitle': 'Add a book to your shelf',
    'editor.editTitle': 'Update book details',
    'editor.description': 'Capture the essentials first. You can refine catalog and sharing details later.',
    'editor.complete': 'book details complete',
    'editor.basic': 'Basic info',
    'editor.basicText': 'The title and author are required. Everything else can stay flexible.',
    'editor.details': 'Details',
    'editor.detailsText': 'These help people browse and understand what you are sharing.',
    'editor.availability': 'Availability',
    'editor.availabilityText': 'Set expectations before the book appears in group catalogs.',
    'editor.preview': 'Preview note',
    'editor.previewText': 'A short note makes the card feel personal without overwhelming readers.',
    'editor.titleLabel': 'Title',
    'editor.authorLabel': 'Author',
    'editor.cover': 'Cover photo',
    'editor.coverHint': 'Click to add a cover image.',
    'editor.coverTypeError': 'Please choose an image file.',
    'editor.coverSizeError': 'Cover image must be 3 MB or smaller.',
    'editor.descriptionLabel': 'Description',
    'editor.notSpecified': 'Not specified',
    'editor.isbn': 'ISBN',
    'editor.save': 'Save changes',
    'editor.add': 'Add book',
    'editor.cancel': 'Cancel',
    'editor.view': 'View book',
    'groups.eyebrow': 'Reading groups',
    'groups.title': 'Groups',
    'groups.subtitle': 'Create private reading rooms, discover open groups, and share catalog shelves with people you trust.',
    'groups.sections': 'Group sections',
    'groups.myGroups': 'My groups',
    'groups.discover': 'Discover',
    'groups.invitations': 'Invitations',
    'groups.yourGroups': 'Your groups',
    'groups.myGroupsText': 'Groups where your membership is active.',
    'groups.loading': 'Loading groups...',
    'groups.open': 'Open',
    'groups.private': 'Private',
    'groups.inviteCode': 'Invite code',
    'groups.openGroup': 'Open group',
    'groups.edit': 'Edit',
    'groups.editGroup': 'Edit group',
    'groups.editText': 'Update the group name, description, or visibility.',
    'groups.save': 'Save changes',
    'groups.cancelEdit': 'Cancel edit',
    'groups.leave': 'Leave group',
    'groups.leaveConfirm': 'Leave "{name}"?',
    'groups.emptyMine': 'No groups yet',
    'groups.emptyMineText': 'Create a group or join one below.',
    'groups.joinPrivate': 'Join private group',
    'groups.joinPrivateText': 'Use an invite code from another member.',
    'groups.invitePlaceholder': 'Paste code',
    'groups.joinPrivateButton': 'Join private',
    'groups.create': 'Create group',
    'groups.createText': 'Private groups generate an invite code automatically.',
    'groups.name': 'Name',
    'groups.description': 'Description',
    'groups.descriptionPlaceholder': 'What this group reads or how members exchange books.',
    'groups.visibility': 'Visibility',
    'groups.privateHelp': 'Best for invite-only groups. An invite code will be generated.',
    'groups.openHelp': 'Anyone can find and join this group.',
    'groups.findOpen': 'Find open groups',
    'groups.findOpenText': 'Search public groups you can join directly.',
    'groups.search': 'Search',
    'groups.searchPlaceholder': 'Group name',
    'groups.join': 'Join',
    'groups.emptyDiscover': 'No open groups found',
    'groups.emptyDiscoverText': 'Try another search or create your own group.',
    'groups.loadError': 'Could not load your groups.',
    'groups.searchError': 'Could not search groups.',
    'groups.createError': 'Could not create group.',
    'groups.updateError': 'Could not update group.',
    'groups.joinError': 'Could not join group.',
    'groups.joinPrivateError': 'Could not join private group.',
    'groups.leaveError': 'Could not leave group.',
    'groups.created': '"{name}" was created.',
    'groups.updated': '"{name}" was updated.',
    'groups.joined': 'You joined "{name}".',
    'groups.left': 'You left "{name}".',
    'profile.account': 'Account settings',
    'profile.title': 'Profile',
    'profile.loading': 'Loading profile...',
    'profile.changeAvatar': 'Change avatar',
    'profile.uploading': 'Uploading...',
    'profile.uploadingAvatar': 'Uploading avatar...',
    'profile.reputation': 'Reputation',
    'profile.memberSince': 'Member since',
    'profile.email': 'Email',
    'profile.firstName': 'First name',
    'profile.lastName': 'Last name',
    'profile.bio': 'Bio',
    'profile.bioPlaceholder': 'A short note about your reading taste, exchange preferences, or favorite shelves.',
    'profile.bioHelp': 'This may be visible to people you share books with. Never include passwords or private tokens.',
    'profile.bioWarning': 'Do not store passwords, tokens, API keys, or other sensitive data in your public bio.',
    'profile.save': 'Save profile',
    'profile.reset': 'Reset changes',
    'profile.notAvailable': 'Not available',
    'profile.updated': 'Profile updated successfully.',
    'profile.avatarUpdated': 'Avatar updated successfully.',
    'profile.avatarTypeError': 'Please choose an image file.',
    'profile.avatarSizeError': 'Avatar must be 5 MB or smaller.',
    'profile.genericError': 'Something went wrong. Please try again.',
    'profile.unavailable': 'Profile is unavailable',
    'profile.unavailableText': 'We could not load account data right now. Please refresh the page.',
  },
  uk: {
    'nav.home': 'Головна',
    'nav.books': 'Книги',
    'nav.groups': 'Групи',
    'nav.openProfile': 'Відкрити профіль',
    'nav.logout': 'Вийти',
    'nav.switchLanguage': 'Змінити мову',
    'home.title': 'Ваш читацький простір',
    'home.description': 'Керуйте книгами, вступайте в читацькі групи, діліться каталогами та відстежуйте заявки в одному місці.',
    'home.collection': 'Колекція',
    'home.groups': 'Групи',
    'home.available': 'Доступні',
    'home.myBooks': 'Мої книги',
    'home.myBooksHint': 'Додавайте й упорядковуйте свою колекцію',
    'home.groupsHint': 'Знаходьте, створюйте й керуйте читацькими групами',
    'home.recent': 'Останні оновлення',
    'home.latestBooks': 'Нові книги',
    'home.viewLibrary': 'Відкрити бібліотеку',
    'home.noBooks': 'Книг ще немає',
    'home.noBooksHint': 'Додайте першу книгу. Пізніше її можна буде поширити в групах.',
    'home.addFirstBook': 'Додати першу книгу',
    'home.groupActivity': 'Активність груп',
    'home.yourCircles': 'Ваші групи',
    'home.noGroups': 'Груп ще немає',
    'home.noGroupsHint': 'Створіть приватну групу або перегляньте відкриті.',
    'home.browseGroups': 'Переглянути групи',
    'home.workflow.addTitle': 'Додавайте книги',
    'home.workflow.addText': 'Зберігайте мову, стан, статус і опис кожної книги.',
    'home.workflow.shareTitle': 'Діліться в групах',
    'home.workflow.shareText': 'Додавайте вибрані книги в каталог групи та керуйте видимістю.',
    'home.workflow.requestsTitle': 'Обробляйте заявки',
    'home.workflow.requestsText': 'Підтверджуйте, відхиляйте, скасовуйте, повертайте й оцінюйте позики.',
    'home.profileSettings': 'Налаштування акаунта',
    'home.profileText': 'Оновіть профіль, аватар, біо та перегляньте репутацію.',
    'home.openProfile': 'Відкрити профіль',
    'books.eyebrow': 'Особиста колекція',
    'books.title': 'Мої книги',
    'books.addBook': 'Додати книгу',
    'books.total': 'Усього книг',
    'books.ready': 'Готові ділитися',
    'books.search': 'Пошук у бібліотеці',
    'books.searchPlaceholder': 'Назва, автор, жанр або мова',
    'books.status': 'Статус',
    'books.sort': 'Сортування',
    'books.all': 'Усі',
    'books.newest': 'Новіші',
    'books.titleSort': 'Назва',
    'books.authorSort': 'Автор',
    'books.grid': 'Сітка',
    'books.list': 'Список',
    'books.loading': 'Завантаження книг...',
    'books.open': 'Відкрити',
    'books.edit': 'Редагувати',
    'books.delete': 'Видалити',
    'books.genre': 'Жанр',
    'books.language': 'Мова',
    'books.year': 'Рік',
    'books.condition': 'Стан',
    'books.added': 'Додано',
    'books.emptyTitle': 'Колекція порожня',
    'books.emptyText': 'Додайте першу книгу, а потім поширюйте вибрані книги в групах.',
    'editor.back': 'Назад до бібліотеки',
    'editor.new': 'Нова книга',
    'editor.edit': 'Редагування книги',
    'editor.newTitle': 'Додайте книгу на свою полицю',
    'editor.editTitle': 'Оновіть дані книги',
    'editor.description': 'Спершу заповніть основне. Каталог і поширення можна уточнити пізніше.',
    'editor.complete': 'даних книги заповнено',
    'editor.basic': 'Основна інформація',
    'editor.basicText': 'Назва й автор обов’язкові. Решту можна заповнити пізніше.',
    'editor.details': 'Деталі',
    'editor.detailsText': 'Це допоможе іншим краще знаходити й розуміти книгу.',
    'editor.availability': 'Доступність',
    'editor.availabilityText': 'Вкажіть очікування перед появою книги в каталогах груп.',
    'editor.preview': 'Короткий опис',
    'editor.previewText': 'Невелика нотатка робить картку книги зрозумілішою та живішою.',
    'editor.titleLabel': 'Назва',
    'editor.authorLabel': 'Автор',
    'editor.cover': 'Фото обкладинки',
    'editor.coverHint': 'Натисніть, щоб додати зображення обкладинки.',
    'editor.coverTypeError': 'Будь ласка, оберіть файл зображення.',
    'editor.coverSizeError': 'Зображення обкладинки має бути не більше 3 МБ.',
    'editor.descriptionLabel': 'Опис',
    'editor.notSpecified': 'Не вказано',
    'editor.isbn': 'ISBN',
    'editor.save': 'Зберегти',
    'editor.add': 'Додати книгу',
    'editor.cancel': 'Скасувати',
    'editor.view': 'Переглянути книгу',
    'groups.eyebrow': 'Читацькі групи',
    'groups.title': 'Групи',
    'groups.subtitle': 'Створюйте приватні читацькі кімнати, знаходьте відкриті групи та діліться каталогами з людьми, яким довіряєте.',
    'groups.sections': 'Розділи груп',
    'groups.myGroups': 'Мої групи',
    'groups.discover': 'Пошук',
    'groups.invitations': 'Запрошення',
    'groups.yourGroups': 'Ваші групи',
    'groups.myGroupsText': 'Групи, де ваша участь активна.',
    'groups.loading': 'Завантаження груп...',
    'groups.open': 'Відкрита',
    'groups.private': 'Приватна',
    'groups.inviteCode': 'Код запрошення',
    'groups.openGroup': 'Відкрити групу',
    'groups.edit': 'Редагувати',
    'groups.editGroup': 'Редагувати групу',
    'groups.editText': 'Оновіть назву, опис або видимість групи.',
    'groups.save': 'Зберегти зміни',
    'groups.cancelEdit': 'Скасувати',
    'groups.leave': 'Вийти з групи',
    'groups.leaveConfirm': 'Вийти з "{name}"?',
    'groups.emptyMine': 'Груп ще немає',
    'groups.emptyMineText': 'Створіть групу або приєднайтесь нижче.',
    'groups.joinPrivate': 'Приєднатися до приватної групи',
    'groups.joinPrivateText': 'Використайте код запрошення від іншого учасника.',
    'groups.invitePlaceholder': 'Вставте код',
    'groups.joinPrivateButton': 'Приєднатися',
    'groups.create': 'Створити групу',
    'groups.createText': 'Для приватних груп код запрошення створюється автоматично.',
    'groups.name': 'Назва',
    'groups.description': 'Опис',
    'groups.descriptionPlaceholder': 'Що читає група або як учасники обмінюються книгами.',
    'groups.visibility': 'Видимість',
    'groups.privateHelp': 'Найкраще для груп лише за запрошенням. Код буде створено автоматично.',
    'groups.openHelp': 'Будь-хто може знайти й приєднатися до цієї групи.',
    'groups.findOpen': 'Знайти відкриті групи',
    'groups.findOpenText': 'Шукайте публічні групи, до яких можна приєднатися одразу.',
    'groups.search': 'Пошук',
    'groups.searchPlaceholder': 'Назва групи',
    'groups.join': 'Приєднатися',
    'groups.emptyDiscover': 'Відкритих груп не знайдено',
    'groups.emptyDiscoverText': 'Спробуйте інший пошук або створіть власну групу.',
    'groups.loadError': 'Не вдалося завантажити ваші групи.',
    'groups.searchError': 'Не вдалося знайти групи.',
    'groups.createError': 'Не вдалося створити групу.',
    'groups.updateError': 'Не вдалося оновити групу.',
    'groups.joinError': 'Не вдалося приєднатися до групи.',
    'groups.joinPrivateError': 'Не вдалося приєднатися до приватної групи.',
    'groups.leaveError': 'Не вдалося вийти з групи.',
    'groups.created': 'Групу "{name}" створено.',
    'groups.updated': 'Групу "{name}" оновлено.',
    'groups.joined': 'Ви приєдналися до "{name}".',
    'groups.left': 'Ви вийшли з "{name}".',
    'profile.account': 'Налаштування акаунта',
    'profile.title': 'Профіль',
    'profile.loading': 'Завантаження профілю...',
    'profile.changeAvatar': 'Змінити аватар',
    'profile.uploading': 'Завантаження...',
    'profile.uploadingAvatar': 'Аватар завантажується...',
    'profile.reputation': 'Репутація',
    'profile.memberSince': 'Учасник з',
    'profile.email': 'Email',
    'profile.firstName': 'Ім’я',
    'profile.lastName': 'Прізвище',
    'profile.bio': 'Біо',
    'profile.bioPlaceholder': 'Коротко про читацькі смаки, обмін книгами або улюблені полиці.',
    'profile.bioHelp': 'Це можуть бачити люди, з якими ви ділитеся книгами. Не додавайте паролі або приватні токени.',
    'profile.bioWarning': 'Не зберігайте паролі, токени, API-ключі або інші чутливі дані в публічному біо.',
    'profile.save': 'Зберегти профіль',
    'profile.reset': 'Скинути зміни',
    'profile.notAvailable': 'Недоступно',
    'profile.updated': 'Профіль успішно оновлено.',
    'profile.avatarUpdated': 'Аватар успішно оновлено.',
    'profile.avatarTypeError': 'Будь ласка, оберіть файл зображення.',
    'profile.avatarSizeError': 'Аватар має бути не більше 5 МБ.',
    'profile.genericError': 'Щось пішло не так. Спробуйте ще раз.',
    'profile.unavailable': 'Профіль недоступний',
    'profile.unavailableText': 'Не вдалося завантажити дані акаунта. Оновіть сторінку.',
  },
} as const;

const initialLocale = localStorage.getItem(STORAGE_KEY) === 'uk' ? 'uk' : 'en';
const locale = ref<AppLocale>(initialLocale);

export const currentLocale = computed(() => locale.value);
export const localeLabel = computed(() => (locale.value === 'en' ? 'EN' : 'UA'));

export function setLocale(nextLocale: AppLocale) {
  locale.value = nextLocale;
  localStorage.setItem(STORAGE_KEY, nextLocale);
}

export function toggleLocale() {
  setLocale(locale.value === 'en' ? 'uk' : 'en');
}

export function t(key: keyof typeof messages.en) {
  return messages[locale.value][key] ?? messages.en[key] ?? key;
}
